#To Store Secrets for Mongo DB service.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque     #default
data:            #Convert text to Base64 values to store credentials
  mongo-user: dXNlcm5hbWU=   
  mongo-password: cGFzc3dvcmQ=